import { Geist, Geist_Mono, Inter } from 'next/font/google'; // Consolidated imports, Poppins removed
import './globals.css';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter', // This is crucial for Tailwind integration if Inter is your base sans font
  weight: ['300', '400', '500', '600', '700'], // Added common weights for Inter
});

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'My Portfolio',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${geistSans.variable} ${geistMono.variable}`}
    >
      <head>
        <link rel="stylesheet" href="https://use.typekit.net/qbe1xrn.css" />
      </head>
      <body className="antialiased">{children}</body>
    </html>
  );
}
